#!/bin/bash
####################################################################
# 
# bl-jhalfs-config.sh
#
####################################################################

#------------------------------------------------------------------#
# GENERATE CONFIGURATION FILE

pushd $JHALFS_GIT_DIR
echo "S" | CONFIG_="" KCONFIG_CONFIG=configuration python3 menu/menuconfig.py Config.in 2> /dev/null

#------------------------------------------------------------------#
# SET CONFIG PARAMS

### REV ###
rev=$(grep CONFIG_SYSV=y $BL_CONFIG_OUT)
if [[ -z $rev ]]; then
	rev=systemd
else
	rev=sysv
fi
if [[ $rev == "systemd" ]]; then

	sed -i "s/BOOK_LFS=y/# BOOK_LFS_ is not set/" $JHALFS_CONFIG
	sed -i "s/# BOOK_LFS_SYSD is not set/BOOK_LFS_SYSD=y" $JHALFS_CONFIG

fi

### BRANCH ###
branch=$(grep CONFIG_BRANCH_.*=y $BL_CONFIG_OUT)
branch=${branch##*_}
branch=${branch%=*}


### INSTALL ROOT ###
installroot=$(grep INSTALLROOT $BL_CONFIG_OUT)
installroot=${installroot##*=}
installroot=${installroot//\"/}


echo "rev: $rev"
echo "branch: $branch"
echo "root: $installroot"


popd
