####################################################################
#
# MAKEFILE DEFINITIONS
#
####################################################################

####################################################################
# DISPLAY OUTPUT
####################################################################

BOLD= "[0;1m"
NORMAL= "[0;0m"
BLUE= "[1;34m"

define bold_message
  @echo $(BOLD)"===================================================================="
  @echo $(BLUE)"--------------------------------------------------------------------"
  @echo  $(BOLD)$(1)
  @echo $(BLUE)"--------------------------------------------------------------------"$(NORMAL)
  @echo
endef



####################################################################
# DIRECTORY DEFINITIONS
####################################################################

### TOP LEVEL DIRS ###

TOPDIR = $(shell pwd)
BUILD_DIR = $(TOPDIR)/build
DOC_DIR = $(TOPDIR)/doc
MISC_DIR = $(TOPDIR)/misc
SCRIPTS_DIR = $(TOPDIR)/scripts
XSL_DIR = $(TOPDIR)/xsl


### DOC DIRS ###

HTML_DIR = $(DOC_DIR)/html


### BUILD DIRS ###

BUILD_XML_DIR = $(BUILD_DIR)/xml

BLFS_BOOK_DIR = $(BUILD_XML_DIR)/blfs-xml
JHALFS_DIR = $(BUILD_DIR)/jhalfs
LFS_BOOK_DIR = $(BUILD_XML_DIR)/lfs-xml




####################################################################
# GIT DEFINITIONS
####################################################################

LFS_GIT = https://git.linuxfromscratch.org/lfs
BLFS_GIT = https://git.linuxfromscratch.org/blfs
JHALFS_GIT = https://git.linuxfromscratch.org/jhalfs



####################################################################
# FILE DEFINITIONS
####################################################################

### HTML FILES ###
INDEX_HTML=$(HTML_DIR)/index.html


### SETUP FILES ###
SETUP_CONFIG_IN = $(BUILD_DIR)/setup-config.in
SETUP_CONFIG_OUT = $(BUILD_DIR)/setup-config.out
SETUP_CONFIG_XML = $(BUILD_DIR)/setup-config.xml



####################################################################
# MISC DEFINITIONS
####################################################################

### BROWSER ###
BROWSER ?= lynx

### MENU_CONFIG ###
MENU_CONFIG = python3 $(TOPDIR)/kconfiglib/menuconfig.py


####################################################################
# SCRIPT DEFINITIONS
####################################################################

### SETUP SCRIPTS ###

SETUP_CONFIG_IN_SH = $(SCRIPTS_DIR)/setup/setup-config-in.sh
SETUP_CONFIG_OUT_SH = $(SCRIPTS_DIR)/setup/setup-config-out.sh
SETUP_CONFIG_XML_SH = $(SCRIPTS_DIR)/setup/setup-config-xml.sh
SETUP_LFS_BOOK_SH = $(SCRIPTS_DIR)/setup/setup-lfs-book.sh


### UTIL SCRIPTS ###

UTIL_SETUP_CONFIG_IN_SH = $(SCRIPTS_DIR)/setup/util_setup-config-in.sh
UTIL_SETUP_CONFIG_OUT_SH = $(SCRIPTS_DIR)/setup/util_setup-config-out.sh
UTIL_SETUP_CONFIG_XML_SH = $(SCRIPTS_DIR)/setup/util_setup-config-xml.sh
UTIL_SETUP_GET_BRANCHES_SH = $(SCRIPTS_DIR)/setup/util_setup-get-branches.sh

export
