####################################################################
#
# MAKEFILE DEFINITIONS
#
####################################################################

####################################################################
# DISPLAY OUTPUT
####################################################################

BOLD= "[0;1m"
NORMAL= "[0;0m"
BLUE= "[1;34m"

define bold_message
  @echo $(BOLD)"===================================================================="
  @echo $(BLUE)"--------------------------------------------------------------------"
  @echo  $(BOLD)$(1)
  @echo $(BLUE)"--------------------------------------------------------------------"$(NORMAL)
  @echo
endef



####################################################################
# DIRECTORY DEFINITIONS
####################################################################

#------------------------------------------------------------------#
### TOP LEVEL DIRS ###

TOPDIR = $(shell pwd)
BUILD_DIR = $(TOPDIR)/build
DOC_DIR = $(TOPDIR)/doc
MISC_DIR = $(TOPDIR)/misc
SCRIPTS_DIR = $(TOPDIR)/scripts
XSL_DIR = $(TOPDIR)/xsl


#------------------------------------------------------------------#
### DOC DIRS ###

HTML_DIR = $(DOC_DIR)/html


#------------------------------------------------------------------#
### BUILD DIRS ###

BUILD_XML_DIR = $(BUILD_DIR)/xml


#------------------------------------------------------------------#
### BUILDLFS DIRS ###

LFS ?= /mnt/lfs
JHALFS_MNT = $(LFS)/jhalfs
LFS_JHALFS_DIR = $(BUILD_DIR)/jhalfs


#------------------------------------------------------------------#
### SETUP DIRS ###

LFS_BOOK_DIR = $(BUILD_XML_DIR)/lfs-xml



####################################################################
# GIT DEFINITIONS
####################################################################

LFS_GIT = https://git.linuxfromscratch.org/lfs
BLFS_GIT = https://git.linuxfromscratch.org/blfs
JHALFS_GIT = https://git.linuxfromscratch.org/jhalfs



####################################################################
# FILE DEFINITIONS
####################################################################

#------------------------------------------------------------------#
### BUILDLFS FILES ###

JHALFS_CONFIGIN = $(LFS_JHALFS_DIR)/Config.in
JHALFS_PACKINSTALL = $(MISC_DIR)/packInstall.sh
JHALFS_PACKXML = $(MISC_DIR)/packageManager.xml
JHALFS_DIFFCONVERT = $(BUILD_DIR)/difflog-convert
RUN_JHALFS = $(JHALFS_MNT)/done

#------------------------------------------------------------------#
### HTML FILES ###
INDEX_HTML=$(HTML_DIR)/index.html


#------------------------------------------------------------------#
### SETUP FILES ###
SETUP_CONFIG_IN = $(BUILD_DIR)/setup-config.in
SETUP_CONFIG_OUT = $(BUILD_DIR)/setup-config.out
SETUP_CONFIG_XML = $(BUILD_DIR)/setup-config.xml



####################################################################
# MISC DEFINITIONS
####################################################################

### BROWSER ###
BROWSER ?= lynx

### MENU_CONFIG ###
MENU_CONFIG = python3 $(TOPDIR)/kconfiglib/menuconfig.py


####################################################################
# SCRIPT DEFINITIONS
####################################################################

#------------------------------------------------------------------#
### BUILDLFS SCRIPTS ###

BUILDLFS_GET_JHALFS_SH = $(SCRIPTS_DIR)/build/buildlfs-get-jhalfs.sh
BUILDLFS_JHALFS_MENUCONFIG_SH = $(SCRIPTS_DIR)/build/buildlfs-jhalfs-menuconfig.sh
BUILDLFS_PRE_JHALFS_SH = $(SCRIPTS_DIR)/build/buildlfs-pre-jhalfs.sh
BUILDLFS_JHALFS_DIFFCONVERT_SH = $(SCRIPTS_DIR)/build/buildlfs-jhalfs-diffconvert.sh
BUILDLFS_RUN_JHALFS_SH = $(SCRIPTS_DIR)/build/buildlfs-run-jhalfs.sh

### BUILDLFS UTIL SCRIPTS ###

UTIL_BUILDLFS_PKGMGT_SH = $(SCRIPTS_DIR)/build/util_buildlfs-pkgmgt.sh
UTIL_BUILDLFS_JHALFS_CONFIGIN_SH = $(SCRIPTS_DIR)/build/util_buildlfs-jhalfs-configin.sh


#------------------------------------------------------------------#
### SETUP SCRIPTS ###

SETUP_CONFIG_IN_SH = $(SCRIPTS_DIR)/setup/setup-config-in.sh
SETUP_CONFIG_OUT_SH = $(SCRIPTS_DIR)/setup/setup-config-out.sh
SETUP_CONFIG_XML_SH = $(SCRIPTS_DIR)/setup/setup-config-xml.sh
SETUP_LFS_BOOK_SH = $(SCRIPTS_DIR)/setup/setup-lfs-book.sh

### SETUP UTIL SCRIPTS ###

UTIL_SETUP_CONFIG_IN_SH = $(SCRIPTS_DIR)/setup/util_setup-config-in.sh
UTIL_SETUP_CONFIG_OUT_SH = $(SCRIPTS_DIR)/setup/util_setup-config-out.sh
UTIL_SETUP_CONFIG_XML_SH = $(SCRIPTS_DIR)/setup/util_setup-config-xml.sh
UTIL_SETUP_GET_BRANCHES_SH = $(SCRIPTS_DIR)/setup/util_setup-get-branches.sh

export
